export interface EmojiDef {
  char: string;
  shortcodes: string[];
}

// A curated set of common emojis with WhatsApp-style shortcodes (no colon).
// One entry per character; shortcodes include common aliases.
export const EMOJIS: EmojiDef[] = [
  { char: '😀', shortcodes: ['grin', 'happy'] },
  { char: '😃', shortcodes: ['smiley'] },
  { char: '😄', shortcodes: ['smile'] },
  { char: '😁', shortcodes: ['grinbeam', 'beaming'] },
  { char: '😆', shortcodes: ['laughing', 'lol'] },
  { char: '😅', shortcodes: ['sweat_smile', 'sweatsmile'] },
  { char: '🤣', shortcodes: ['rofl', 'rolling'] },
  { char: '😂', shortcodes: ['joy', 'laugh', 'tears'] },
  { char: '🙂', shortcodes: ['slight_smile', 'slightsmile'] },
  { char: '😉', shortcodes: ['wink'] },
  { char: '😊', shortcodes: ['blush'] },
  { char: '😇', shortcodes: ['innocent', 'halo'] },
  { char: '🥰', shortcodes: ['hearts', 'love'] },
  { char: '😍', shortcodes: ['heart_eyes', 'hearteyes'] },
  { char: '😘', shortcodes: ['kissing_heart', 'kiss'] },
  { char: '😜', shortcodes: ['stuck_out_tongue_winking_eye', 'winktongue'] },
  { char: '😝', shortcodes: ['tongue', 'prank'] },
  { char: '😋', shortcodes: ['yum', 'tasty'] },
  { char: '😎', shortcodes: ['cool', 'sunglasses'] },
  { char: '🤓', shortcodes: ['nerd'] },
  { char: '🧐', shortcodes: ['monocle'] },
  { char: '🤔', shortcodes: ['think', 'thinking'] },
  { char: '🤨', shortcodes: ['raised_eyebrow', 'eyebrow', 'sus'] },
  { char: '😏', shortcodes: ['smirk'] },
  { char: '😴', shortcodes: ['sleep', 'zzz'] },
  { char: '😪', shortcodes: ['sleepy'] },
  { char: '🥱', shortcodes: ['yawn'] },
  { char: '😢', shortcodes: ['cry'] },
  { char: '😭', shortcodes: ['sob', 'crying'] },
  { char: '😱', shortcodes: ['scream'] },
  { char: '😨', shortcodes: ['fearful', 'scared'] },
  { char: '😰', shortcodes: ['anxiety', 'nervous'] },
  { char: '😥', shortcodes: ['disappointed_relieved'] },
  { char: '😓', shortcodes: ['sweat', 'phew'] },
  { char: '😞', shortcodes: ['disappointed', 'sad'] },
  { char: '😔', shortcodes: ['pensive'] },
  { char: '😟', shortcodes: ['worried'] },
  { char: '😕', shortcodes: ['confused'] },
  { char: '🙁', shortcodes: ['frown'] },
  { char: '☹️', shortcodes: ['frown2'] },
  { char: '😮', shortcodes: ['open_mouth', 'oh'] },
  { char: '😯', shortcodes: ['hushed'] },
  { char: '😲', shortcodes: ['astonished', 'wow'] },
  { char: '😳', shortcodes: ['flushed'] },
  { char: '🥺', shortcodes: ['pleading', 'beg'] },
  { char: '😡', shortcodes: ['angry', 'rage'] },
  { char: '😠', shortcodes: ['enraged'] },
  { char: '🤬', shortcodes: ['swearing', 'cuss'] },
  { char: '😈', shortcodes: ['smiling_imp', 'devil'] },
  { char: '👿', shortcodes: ['imp'] },
  { char: '💀', shortcodes: ['skull', 'death'] },
  { char: '🤯', shortcodes: ['exploding_head', 'mindblown'] },
  { char: '🥳', shortcodes: ['party', 'celebrate'] },
  { char: '🤠', shortcodes: ['cowboy'] },
  { char: '🤒', shortcodes: ['sick'] },
  { char: '🤕', shortcodes: ['hurt', 'bandage'] },
  { char: '🤧', shortcodes: ['sneeze'] },
  { char: '😷', shortcodes: ['mask'] },
  { char: '🥵', shortcodes: ['hot'] },
  { char: '🥶', shortcodes: ['cold'] },
  { char: '🥴', shortcodes: ['woozy', 'drunk'] },
  { char: '😵', shortcodes: ['dizzy'] },
  { char: '🤐', shortcodes: ['zipper_mouth', 'mute'] },

  { char: '❤️', shortcodes: ['heart', 'love', 'redheart'] },
  { char: '🧡', shortcodes: ['orange_heart', 'orangeheart'] },
  { char: '💛', shortcodes: ['yellow_heart', 'yellowheart'] },
  { char: '💚', shortcodes: ['green_heart', 'greenheart'] },
  { char: '💙', shortcodes: ['blue_heart', 'blueheart'] },
  { char: '💜', shortcodes: ['purple_heart', 'purpleheart'] },
  { char: '🖤', shortcodes: ['black_heart', 'blackheart'] },
  { char: '🤍', shortcodes: ['white_heart', 'whiteheart'] },
  { char: '🤎', shortcodes: ['brown_heart', 'brownheart'] },
  { char: '💔', shortcodes: ['broken_heart', 'brokenheart'] },
  { char: '❤️‍🔥', shortcodes: ['heart_on_fire', 'heartfire'] },
  { char: '💕', shortcodes: ['two_hearts', 'twohearts'] },
  { char: '💖', shortcodes: ['sparkling_heart', 'sparkleheart'] },
  { char: '💯', shortcodes: ['hundred', '100'] },

  { char: '👍', shortcodes: ['thumbsup', 'thumbs', 'like', '+1'] },
  { char: '👎', shortcodes: ['thumbsdown', 'dislike', '-1'] },
  { char: '👌', shortcodes: ['ok', 'okay'] },
  { char: '✌️', shortcodes: ['peace', 'victory'] },
  { char: '🤞', shortcodes: ['fingers_crossed', 'crossed', 'fingerscrossed'] },
  { char: '🤟', shortcodes: ['love_you', 'ily'] },
  { char: '🤘', shortcodes: ['rock'] },
  { char: '🤙', shortcodes: ['call', 'shaka'] },
  { char: '👈', shortcodes: ['point_left', 'left'] },
  { char: '👉', shortcodes: ['point_right', 'right'] },
  { char: '👆', shortcodes: ['point_up', 'up'] },
  { char: '👇', shortcodes: ['point_down', 'down'] },
  { char: '☝️', shortcodes: ['one', 'point_up_2'] },
  { char: '✋', shortcodes: ['hand', 'stop', 'raised'] },
  { char: '🤚', shortcodes: ['raised_back', 'palm'] },
  { char: '👋', shortcodes: ['wave', 'hi', 'hello'] },
  { char: '👏', shortcodes: ['clap', 'applause'] },
  { char: '🙌', shortcodes: ['raised_hands', 'hooray'] },
  { char: '🙏', shortcodes: ['pray', 'thanks', 'please'] },
  { char: '🤝', shortcodes: ['handshake', 'deal'] },
  { char: '💪', shortcodes: ['muscle', 'strong', 'flex'] },
  { char: '✍️', shortcodes: ['write', 'writing'] },
  { char: '👀', shortcodes: ['eyes', 'look'] },
  { char: '🧠', shortcodes: ['brain', 'smart'] },

  { char: '🔥', shortcodes: ['fire', 'lit'] },
  { char: '✨', shortcodes: ['sparkles', 'shine'] },
  { char: '⭐', shortcodes: ['star'] },
  { char: '🌟', shortcodes: ['star2', 'glowing'] },
  { char: '💫', shortcodes: ['dizzy', 'stars'] },
  { char: '⚡', shortcodes: ['zap', 'lightning'] },
  { char: '☀️', shortcodes: ['sun', 'sunny'] },
  { char: '🌙', shortcodes: ['moon', 'night'] },
  { char: '🌈', shortcodes: ['rainbow', 'pride'] },
  { char: '❄️', shortcodes: ['snowflake', 'snow', 'cold'] },
  { char: '💧', shortcodes: ['droplet', 'water'] },
  { char: '🌊', shortcodes: ['wave', 'ocean'] },

  { char: '🎉', shortcodes: ['tada', 'party2', 'hooray2'] },
  { char: '🎊', shortcodes: ['confetti'] },
  { char: '🎈', shortcodes: ['balloon'] },
  { char: '🎁', shortcodes: ['gift', 'present'] },
  { char: '🎂', shortcodes: ['cake', 'birthday'] },
  { char: '🍕', shortcodes: ['pizza'] },
  { char: '🍔', shortcodes: ['burger'] },
  { char: '🍟', shortcodes: ['fries'] },
  { char: '🌮', shortcodes: ['taco'] },
  { char: '🍣', shortcodes: ['sushi'] },
  { char: '🍜', shortcodes: ['ramen', 'noodles'] },
  { char: '🍦', shortcodes: ['icecream'] },
  { char: '🍩', shortcodes: ['donut'] },
  { char: '🍪', shortcodes: ['cookie'] },
  { char: '🍫', shortcodes: ['chocolate'] },
  { char: '☕', shortcodes: ['coffee'] },
  { char: '🍵', shortcodes: ['tea'] },
  { char: '🍺', shortcodes: ['beer'] },
  { char: '🍷', shortcodes: ['wine'] },
  { char: '🥂', shortcodes: ['cheers', 'champagne'] },

  { char: '⚽', shortcodes: ['soccer', 'football'] },
  { char: '🏀', shortcodes: ['basketball'] },
  { char: '🏆', shortcodes: ['trophy', 'win'] },
  { char: '🎮', shortcodes: ['game', 'gaming'] },
  { char: '🎲', shortcodes: ['dice'] },
  { char: '🎵', shortcodes: ['note', 'music'] },
  { char: '🎶', shortcodes: ['notes', 'song'] },
  { char: '🎸', shortcodes: ['guitar'] },
  { char: '✈️', shortcodes: ['plane', 'fly'] },
  { char: '🚗', shortcodes: ['car'] },
  { char: '🚕', shortcodes: ['taxi'] },
  { char: '🚲', shortcodes: ['bike', 'bicycle'] },
  { char: '🚀', shortcodes: ['rocket', 'launch'] },

  { char: '🏠', shortcodes: ['home', 'house'] },
  { char: '💰', shortcodes: ['money', 'cash'] },
  { char: '💵', shortcodes: ['dollar'] },
  { char: '💳', shortcodes: ['card'] },
  { char: '✉️', shortcodes: ['email', 'envelope', 'mail'] },
  { char: '📧', shortcodes: ['e-mail'] },
  { char: '📦', shortcodes: ['package', 'box'] },
  { char: '📱', shortcodes: ['phone', 'mobile'] },
  { char: '💻', shortcodes: ['laptop', 'computer'] },
  { char: '💡', shortcodes: ['idea', 'bulb', 'lightbulb'] },
  { char: '🔔', shortcodes: ['bell', 'alert'] },
  { char: '🔒', shortcodes: ['lock'] },
  { char: '🔑', shortcodes: ['key'] },
  { char: '🛠️', shortcodes: ['tools', 'fix'] },
  { char: '⚙️', shortcodes: ['gear', 'settings'] },
  { char: '🔗', shortcodes: ['link'] },
  { char: '📎', shortcodes: ['paperclip', 'clip'] },

  { char: '✅', shortcodes: ['white_check_mark', 'check', 'done'] },
  { char: '✔️', shortcodes: ['heavy_check_mark', 'ok2'] },
  { char: '❌', shortcodes: ['x', 'cross', 'no'] },
  { char: '❎', shortcodes: ['cross_mark'] },
  { char: '❓', shortcodes: ['question', '?'] },
  { char: '❗', shortcodes: ['exclamation', '!'] },
  { char: '⚠️', shortcodes: ['warning', 'warn'] },
  { char: '🔴', shortcodes: ['red_circle', 'red'] },
  { char: '🟠', shortcodes: ['orange_circle', 'orange'] },
  { char: '🟡', shortcodes: ['yellow_circle', 'yellow'] },
  { char: '🟢', shortcodes: ['green_circle', 'green'] },
  { char: '🔵', shortcodes: ['blue_circle', 'blue'] },
  { char: '🟣', shortcodes: ['purple_circle', 'purple'] },

  { char: '🐶', shortcodes: ['dog'] },
  { char: '🐱', shortcodes: ['cat'] },
  { char: '🐭', shortcodes: ['mouse'] },
  { char: '🐹', shortcodes: ['hamster'] },
  { char: '🐰', shortcodes: ['rabbit', 'bunny'] },
  { char: '🦊', shortcodes: ['fox'] },
  { char: '🐻', shortcodes: ['bear'] },
  { char: '🐼', shortcodes: ['panda'] },
  { char: '🐨', shortcodes: ['koala'] },
  { char: '🐯', shortcodes: ['tiger'] },
  { char: '🦁', shortcodes: ['lion'] },
  { char: '🐮', shortcodes: ['cow'] },
  { char: '🐷', shortcodes: ['pig'] },
  { char: '🐸', shortcodes: ['frog'] },
  { char: '🐵', shortcodes: ['monkey'] },
  { char: '🐔', shortcodes: ['chicken'] },
  { char: '🐧', shortcodes: ['penguin'] },
  { char: '🐦', shortcodes: ['bird'] },
  { char: '🦆', shortcodes: ['duck'] },
  { char: '🦉', shortcodes: ['owl'] },
  { char: '🐝', shortcodes: ['bee'] },
  { char: '🦋', shortcodes: ['butterfly'] },
  { char: '🐢', shortcodes: ['turtle'] },
  { char: '🐬', shortcodes: ['dolphin'] },
  { char: '🐳', shortcodes: ['whale'] },

  { char: '🌹', shortcodes: ['rose', 'flower'] },
  { char: '🌻', shortcodes: ['sunflower'] },
  { char: '🌷', shortcodes: ['tulip'] },
  { char: '🌸', shortcodes: ['cherry', 'blossom'] },
  { char: '🌳', shortcodes: ['tree'] },
  { char: '🌴', shortcodes: ['palm'] },
  { char: '🌵', shortcodes: ['cactus'] },

  { char: '🇨🇦', shortcodes: ['canada', 'ca'] },
  { char: '🇺🇸', shortcodes: ['us', 'usa', 'america'] },
  { char: '🌍', shortcodes: ['earth', 'world', 'globe'] },
];

/** Find emojis whose shortcode matches a query prefix (colon autocomplete). */
export function searchEmojis(query: string, limit = 8): EmojiDef[] {
  const q = query.toLowerCase().replace(/[:]/g, '');
  if (!q) return [];
  const out: EmojiDef[] = [];
  for (const e of EMOJIS) {
    if (e.shortcodes.some((s) => s.startsWith(q) || s.includes(q))) {
      out.push(e);
      if (out.length >= limit) break;
    }
  }
  return out;
}

/** Emojis for the picker grid, optionally filtered by search text. */
export function pickerEmojis(filter: string): EmojiDef[] {
  const q = filter.trim().toLowerCase();
  if (!q) return EMOJIS.filter((e) => e.shortcodes.length > 0);
  return EMOJIS.filter(
    (e) => e.char.includes(q) || e.shortcodes.some((s) => s.includes(q))
  );
}
